title: "Automation Idea: "
labels: ["New Automation Idea"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to contribute your gitStream automation idea! This template will walk you through all the information we need to evaluate your request and prioritize it for the library. Please fill out each section according to the instructions found in the comments.
  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: "Please describe the challenge this automation would help solve. Is it related to a problem you're facing?"
      value: |
        Insert your overview here
      render: bash
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Have you tried any alternative solutions?
      description: "Please provide info about any alternatives you've tried and why they don't solve your problem."
      value: |
        Describe alternatives you've tried.
      render: bash
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Markdown header
        And some more markdown
  - type: input
    id: has-id
    attributes:
      label: Suggestions
      description: A description about suggestions to help you
    validations:
      required: true
  - type: dropdown
    id: download
    attributes:
      label: Which area of this project could be most improved?
      options:
        - Documentation
        - Pull request review time
        - Bug fix time
        - Release cadence
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Check that box!
      options:
        - label: This one!
          required: true
        - label: I won't stop you if you check this one, too
  - type: markdown
    attributes:
      value: |
        ### The thrilling conclusion
        _to our template_
